### ISSUE TITLE
No idea how to build for iOS version?

### ISSUE THREAD

**Issue by ghost** [pristineio/webrtc-mirror#1]
Hi! Team Pristineio,

I'm using the old version of building the iOS version of tech.pristine.io/build-ios-apprtc/. Is it possible to make a dynamic library that easily integrate on any iOS project? 

Or is possible that every releases of webrtc-mirror, it has a iOS library release?

**Comment by thebehera** [comment]
I'd recommend using cocoapods-> http://cocoadocs.org/docsets/libjingle_peerconnection
If you want to build it yourself use -> https://github.com/pristineio/webrtc-build-scripts/

**Comment by ghost** [comment]
Got download again the repo for webrtc-build-scripts, i will try to test if this will fix my issue on SRTP.
Thank you very much for faster response :) :+1:
