### ISSUE TITLE
How to Use webrtc::DesktopCapturer module instead of cricket::VideoCapturer for windows?

### ISSUE THREAD

**Issue by EbramTawfik** [pristineio/webrtc-mirror#4]
I want to use  [desktop_capture module for native webrtc ](https://chromium.googlesource.com/external/webrtc.git/+/390e64d7ebe15e0e8b21fc1dc49ae3d9b5c545ef/webrtc/modules/desktop_capture/) instead of implementing a new desktop capturer so I want to set the source for peerconnection in `CreateVideoSource` to `webrtc::DesktopCapture` instead of using `cricket::VideoCapturer` as in `CreateVideoSource` you have to use `cricket::VideoCapturer`  

        cricket::VideoCapturer * vc = nullptr;
		if (capturer_internal)
		{
			vc = capturer_internal.get();
		}
		auto v = pc_factory_->CreateVideoSource(vc, NULL);
		auto video_track = pc_factory_->CreateVideoTrack(kVideoLabel, v);

Even if I created a class which inherit from `VideoCapturer`. How to convert `webrtc::DesktopFrame` to `webrtc::VideoFrame` in this [code](https://github.com/radioman/WebRtc.NET/blob/master/WebRtc.NET/src/defaults.cc#L158) ?

**Comment by ArikYa** [comment]
@EbramSamy this is just a mirror of WebRTC. Any specific WebRTC questions should be pointed to their discussion forum: https://groups.google.com/forum/#!forum/discuss-webrtc
